import {
	iconJS,
	iconTS,
	iconHTML,
	iconSASS,
	iconGIT,
	iconGITHUB,
	iconVSCODE,
	iconCSS,
} from '../../../public/svg/icons';

export const projects = [
	{
		id: 'quiz01',
		title: 'Quiz Programação',
		src: '/quiz.png',
		icons: [
			iconJS,
			iconTS,
			iconHTML,
			iconSASS,
			iconGIT,
			iconGITHUB,
			iconVSCODE,
		],
		linkDeploy: 'https://pr-quiz-programming.vercel.app',
		linkRepo: 'https://github.com/code-front-braga/PR-Quiz_Programming',
	},
	{
		id: 'imc02',
		title: 'IMC - Landing Page',
		src: '/bmi.png',
		icons: [iconJS, iconTS, iconHTML, iconCSS, iconGIT, iconGITHUB, iconVSCODE],
		linkDeploy: 'https://pr-body-mass-index.vercel.app',
		linkRepo: 'https://github.com/code-front-braga/PR-Body_Mass_Index',
	},
	{
		id: 'webClock03',
		title: 'Relógio Web',
		src: '/w-clock.png',
		icons: [iconJS, iconTS, iconHTML, iconCSS, iconGIT, iconGITHUB, iconVSCODE],
		linkDeploy: 'https://pr-basic-clock.vercel.app',
		linkRepo: 'https://github.com/code-front-braga/PR-Basic_Clock',
	},
	{
		id: 'sign04',
		title: 'Veja Seu Signo',
		src: '/sign.png',
		icons: [iconJS, iconTS, iconHTML, iconCSS, iconGIT, iconGITHUB, iconVSCODE],
		linkDeploy: 'https://pr-whats-your-zodiac-sign.vercel.app',
		linkRepo: 'https://github.com/code-front-braga/PR-Whats_Your_Zodiac_Sign',
	},
	{
		id: 'chron05',
		title: 'Cronômetro',
		src: '/chronometer.png',
		icons: [iconJS, iconTS, iconHTML, iconCSS, iconGIT, iconGITHUB, iconVSCODE],
		linkDeploy: 'https://pr-chronometer.vercel.app',
		linkRepo: 'https://github.com/code-front-braga/PR-Chronometer',
	},
	{
		id: 'counter06',
		title: 'Contador',
		src: '/counter.png',
		icons: [iconJS, iconTS, iconHTML, iconCSS, iconGIT, iconGITHUB, iconVSCODE],
		linkDeploy: 'https://pr-counter.vercel.app',
		linkRepo: 'https://github.com/code-front-braga/PR-Counter',
	},
	{
		id: 'calc07',
		title: 'Calculadora',
		src: '/calculator.png',
		icons: [iconJS, iconTS, iconHTML, iconCSS, iconGIT, iconGITHUB, iconVSCODE],
		linkDeploy: 'https://pr-basic-calculator.vercel.app',
		linkRepo: 'https://github.com/code-front-braga/PR-Basic_Calculator',
	},
];
