import {
	iconJS,
	iconTS,
	iconHTML,
	iconSASS,
	iconGIT,
	iconGITHUB,
	iconVSCODE,
	iconCSS,
  iconNEXT,
  iconPRISMA,
  iconPOSTGRESQL,
} from './icons';

export const projects = [
	{
		id: 'quiz01',
		title: 'Quiz Programação',
		src: '/quiz.png',
		icons: [
			iconJS,
			iconTS,
			iconHTML,
			iconSASS,
			iconGIT,
			iconGITHUB,
			iconVSCODE,
		],
		linkDeploy: 'https://pr-quiz-programming.vercel.app',
		linkRepo: 'https://github.com/code-front-braga/PR-Quiz_Programming',
	},
	{
		id: 'imc01',
		title: 'IMC - Landing Page',
		src: '/bmi.png',
		icons: [iconJS, iconTS, iconHTML, iconCSS, iconGIT, iconGITHUB, iconVSCODE],
		linkDeploy: 'https://pr-body-mass-index.vercel.app',
		linkRepo: 'https://github.com/code-front-braga/PR-Body_Mass_Index',
	},
  {
    id: 'authtemp02',
    title: 'Template de Cadastro e Login',
    src: '/auth_template.png',
    icons: [iconNEXT, iconJS, iconGIT, iconGITHUB, iconVSCODE, iconPRISMA, iconPOSTGRESQL],
    linkDeploy: 'https://auth-template-zeta.vercel.app/auth',
    linkRepo: 'https://github.com/code-front-braga/auth-template',
  },
  {
    id: 'linkShorter03',
    title: 'Encurtador de Link',
    src: '/shorter.png',
    icons: [iconNEXT, iconJS, iconGIT, iconGITHUB, iconVSCODE, iconPRISMA],
    linkDeploy: 'https://link-shortener-phi-five.vercel.app',
    linkRepo: 'https://github.com/code-front-braga/link-shortener',
  },
  {
    id: 'currency04',
    title: 'Cotação de Moedas',
    src: '/currency.png',
    icons: [iconNEXT, iconJS, iconGIT, iconGITHUB, iconVSCODE],
    linkDeploy: 'https://currency-swift-chi.vercel.app',
    linkRepo: 'https://github.com/code-front-braga/currency_swift',
  },
  {
    id: 'e-listou05',
    title: 'Controle de Compras',
    src: '/elistou.png',
    icons: [iconNEXT, iconJS, iconGIT, iconGITHUB, iconVSCODE, iconPRISMA, iconPOSTGRESQL],
    linkDeploy: 'https://currency-swift-chi.vercel.app',
    linkRepo: 'https://github.com/code-front-braga/e-listou',
  },
];
